# Generated by Django 5.0.13 on 2025-04-01 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=12)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
