# Generated by Django 5.0.13 on 2025-04-01 12:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecAttendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_embedding',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('7:00 AM - 10:00 AM', '07:00-10:00'), ('11:00 AM - 2:00 PM', '11:00-14:00'), ('3:00 PM - 6:00 PM', '15:00-18:00')], max_length=40)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceRecAttendance.user')),
            ],
            options={
                'unique_together': {('user', 'attendance_date', 'time_slot')},
            },
        ),
    ]
